export const env = {
  DATABASE_URL: process.env.DATABASE_URL!,
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
    process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY!,
  NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL:
    process.env.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL!,
  NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL:
    process.env.NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL!,
  GOOGLE_VISION_API_KEY: process.env.GOOGLE_VISION_API_KEY!,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY!,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY!,
};
